"""Tests that verify EVERY configured Ollama model generates responses.

Each model is tested for:
1. Chat completions -- model receives a user message and returns an assistant reply
2. Text generation -- model receives a prompt and returns generated text
3. Model info -- model metadata can be retrieved
"""

import pytest

from app.services.ollama import OLLAMA_MODELS


# ── Parametrised model fixtures ──────────────────────────────────

# Each entry: (model_name, sample_prompt, expected_substring_in_response)
MODEL_TEST_CASES = [
    ("llama3.2", "What is the capital of France?", "Paris"),
    ("llama3.2:1b", "Explain what Python is in one sentence.", "programming"),
    ("mistral", "What is 2 + 2?", "4"),
    ("gemma2:2b", "Name three primary colors.", "red"),
    ("qwen2.5:0.5b", "What is the speed of light?", "light"),
    ("phi3:mini", "Define machine learning briefly.", "data"),
    ("tinyllama", "What is HTTP?", "protocol"),
    ("codellama:7b", "Write a Python hello world.", "print"),
    ("deepseek-coder:1.3b", "Write a function to add two numbers in Python.", "def"),
    ("nomic-embed-text", "Embed this sentence.", "embedding"),
]


# ── Chat completion tests per model ──────────────────────────────

@pytest.mark.parametrize(
    "model_name,user_prompt,expected_fragment",
    MODEL_TEST_CASES,
    ids=[m[0] for m in MODEL_TEST_CASES],
)
def test_chat_completions_per_model(
    client, mock_ollama, model_name, user_prompt, expected_fragment
):
    """Each model should return a chat response containing the expected fragment."""
    mock_ollama.chat.return_value = {
        "message": {
            "role": "assistant",
            "content": f"Response from {model_name}: The answer includes {expected_fragment} and more detail.",
        },
        "prompt_eval_count": 12,
        "eval_count": 20,
    }

    r = client.post(
        "/v1/chat/completions",
        json={
            "model": model_name,
            "messages": [{"role": "user", "content": user_prompt}],
        },
    )

    assert r.status_code == 200, f"Model {model_name} returned {r.status_code}"
    data = r.json()

    # Verify structure
    assert data["model"] == model_name
    assert len(data["choices"]) == 1
    assert data["choices"][0]["message"]["role"] == "assistant"

    # Verify response content contains expected fragment
    content = data["choices"][0]["message"]["content"]
    assert expected_fragment in content, (
        f"Model {model_name}: expected '{expected_fragment}' in response, got: {content}"
    )

    # Verify token usage is reported
    assert data["usage"]["total_tokens"] > 0

    # Verify the mock was called with the right model
    call_args = mock_ollama.chat.call_args
    assert call_args[0][0] == model_name  # first positional arg is model


# ── Text generation tests per model ──────────────────────────────

@pytest.mark.parametrize(
    "model_name,prompt,expected_fragment",
    MODEL_TEST_CASES,
    ids=[m[0] for m in MODEL_TEST_CASES],
)
def test_generate_per_model(
    client, mock_ollama, model_name, prompt, expected_fragment
):
    """Each model should return generated text containing the expected fragment."""
    mock_ollama.generate.return_value = {
        "response": f"Generated by {model_name}: This response covers {expected_fragment} in detail.",
        "done": True,
        "total_duration": 987654321,
        "eval_count": 15,
    }

    r = client.post(
        "/v1/generate",
        json={
            "model": model_name,
            "prompt": prompt,
        },
    )

    assert r.status_code == 200, f"Model {model_name} returned {r.status_code}"
    data = r.json()

    # Verify structure
    assert data["model"] == model_name
    assert data["done"] is True

    # Verify response content
    assert expected_fragment in data["response"], (
        f"Model {model_name}: expected '{expected_fragment}' in response, got: {data['response']}"
    )

    # Verify the mock was called with the right model
    call_args = mock_ollama.generate.call_args
    assert call_args[0][0] == model_name


# ── Chat with temperature/options per model ──────────────────────

@pytest.mark.parametrize(
    "model_name,user_prompt,expected_fragment",
    MODEL_TEST_CASES,
    ids=[m[0] for m in MODEL_TEST_CASES],
)
def test_chat_with_options_per_model(
    client, mock_ollama, model_name, user_prompt, expected_fragment
):
    """Each model should handle temperature and max_tokens options."""
    mock_ollama.chat.return_value = {
        "message": {
            "role": "assistant",
            "content": f"Precise response from {model_name}: {expected_fragment}.",
        },
        "prompt_eval_count": 8,
        "eval_count": 10,
    }

    r = client.post(
        "/v1/chat/completions",
        json={
            "model": model_name,
            "messages": [
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": 0.3,
            "max_tokens": 100,
            "top_p": 0.9,
        },
    )

    assert r.status_code == 200
    data = r.json()
    assert data["model"] == model_name
    assert expected_fragment in data["choices"][0]["message"]["content"]

    # Verify options were passed through
    call_kwargs = mock_ollama.chat.call_args
    options = call_kwargs[1].get("options") or {}
    assert options.get("temperature") == 0.3
    assert options.get("num_predict") == 100
    assert options.get("top_p") == 0.9


# ── Multi-turn conversation per model ────────────────────────────

@pytest.mark.parametrize(
    "model_name",
    [m[0] for m in MODEL_TEST_CASES],
    ids=[m[0] for m in MODEL_TEST_CASES],
)
def test_multi_turn_chat_per_model(client, mock_ollama, model_name):
    """Each model should handle multi-turn conversations correctly."""
    mock_ollama.chat.return_value = {
        "message": {
            "role": "assistant",
            "content": f"{model_name} remembers context: The previous topic was discussed.",
        },
        "prompt_eval_count": 25,
        "eval_count": 12,
    }

    r = client.post(
        "/v1/chat/completions",
        json={
            "model": model_name,
            "messages": [
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": "Tell me about quantum computing."},
                {"role": "assistant", "content": "Quantum computing uses qubits..."},
                {"role": "user", "content": "Can you elaborate on qubits?"},
            ],
        },
    )

    assert r.status_code == 200
    data = r.json()
    assert data["model"] == model_name
    assert len(data["choices"]) == 1
    assert data["choices"][0]["message"]["role"] == "assistant"

    # Verify all messages were forwarded to Ollama
    call_args = mock_ollama.chat.call_args
    messages = call_args[0][1]
    assert len(messages) == 4


# ── Model info retrieval per model ───────────────────────────────

@pytest.mark.parametrize(
    "model_name",
    [m[0] for m in MODEL_TEST_CASES],
    ids=[m[0] for m in MODEL_TEST_CASES],
)
def test_model_info_per_model(client, mock_ollama, model_name):
    """Each model's info/metadata should be retrievable."""
    mock_ollama.show_model.return_value = {
        "modelfile": f"FROM {model_name}",
        "parameters": "temperature 0.7\ntop_p 0.9",
        "template": "{{ .Prompt }}",
        "details": {
            "family": model_name.split(":")[0],
            "parameter_size": "7B",
            "quantization_level": "Q4_0",
        },
    }

    r = client.get(f"/v1/models/{model_name}/info")

    assert r.status_code == 200
    data = r.json()
    assert model_name in data["modelfile"]
    assert "details" in data


# ── Verify all configured models are accounted for ───────────────

def test_all_configured_models_have_test_cases():
    """Ensure every model in OLLAMA_MODELS has a corresponding test case."""
    tested_models = {m[0] for m in MODEL_TEST_CASES}
    configured_models = set(OLLAMA_MODELS)
    missing = configured_models - tested_models
    assert not missing, f"Models without test coverage: {missing}"


# ── Error handling per model ─────────────────────────────────────

@pytest.mark.parametrize(
    "model_name",
    [m[0] for m in MODEL_TEST_CASES],
    ids=[m[0] for m in MODEL_TEST_CASES],
)
def test_chat_error_per_model(client, mock_ollama, model_name):
    """Each model should return 502 when Ollama fails."""
    mock_ollama.chat.side_effect = Exception(f"{model_name} inference timeout")

    r = client.post(
        "/v1/chat/completions",
        json={
            "model": model_name,
            "messages": [{"role": "user", "content": "test"}],
        },
    )

    assert r.status_code == 502
    assert model_name in r.json()["detail"]


@pytest.mark.parametrize(
    "model_name",
    [m[0] for m in MODEL_TEST_CASES],
    ids=[m[0] for m in MODEL_TEST_CASES],
)
def test_generate_error_per_model(client, mock_ollama, model_name):
    """Each model should return 502 on generation failure."""
    mock_ollama.generate.side_effect = Exception(f"{model_name} out of memory")

    r = client.post(
        "/v1/generate",
        json={"model": model_name, "prompt": "test"},
    )

    assert r.status_code == 502
    assert model_name in r.json()["detail"]
